### ISSUE TITLE
datalad-extensions FAILs in test_base

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-ukbiobank#91]
e.g. https://github.com/datalad/datalad-extensions/runs/7694639181?check_suite_focus=true#step:10:190

```
FAIL: datalad_ukbiobank.tests.test_init.test_base
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/datalad/tests/utils_pytest.py", line 954, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/datalad_ukbiobank/tests/test_init.py", line 26, in test_base
    for b in ['git-annex', 'incoming', 'incoming-native', DEFAULT_BRANCH])
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/datalad/tests/utils_pytest.py", line [191](https://github.com/datalad/datalad-extensions/runs/7694639181?check_suite_focus=true#step:10:192), in assert_true
    assert expr
AssertionError:
```

**Comment by mih** [comment]
I have merged https://github.com/datalad/datalad-ukbiobank/pull/93 and https://github.com/datalad/datalad-ukbiobank/pull/98 which addressed a bunch of issues. The tests pass again here. I assume/hope this is also fixing the datalad-extensions CI
